# Generated by Django 5.2.14 on 2026-05-13 16:12

import core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('birth_date', models.DateField(blank=True, null=True, validators=[core.validators.validate_age_18_plus], verbose_name='birth date')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone_by_format_375_29], verbose_name='phone')),
                ('is_vip', models.BooleanField(default=False, verbose_name='VIP customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'customer profile',
                'verbose_name_plural': 'customer profiles',
                'indexes': [models.Index(fields=['phone'], name='customer_phone_idx'), models.Index(fields=['is_vip'], name='customer_vip_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='full name')),
                ('position', models.CharField(max_length=128, verbose_name='position')),
                ('phone', models.CharField(max_length=20, unique=True, validators=[core.validators.validate_phone_by_format_375_29], verbose_name='phone')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'employee profile',
                'verbose_name_plural': 'employee profiles',
                'indexes': [models.Index(fields=['phone'], name='employee_phone_idx'), models.Index(fields=['is_active'], name='employee_active_idx')],
            },
        ),
    ]
