# Generated by Django 5.2.14 on 2026-05-17 19:59

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_employeeprofile_suppliers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeprofile",
            name="birth_date",
            field=models.DateField(
                blank=True,
                null=True,
                validators=[core.validators.validate_age_18_plus],
                verbose_name="birth date",
            ),
        ),
    ]
