# Generated by Django 5.2.14 on 2026-09-07 19:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_contact_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_text',
            field=models.TextField(blank=True, verbose_name='certificate text'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='requisites',
            field=models.TextField(blank=True, verbose_name='requisites'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='video URL'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='contact',
            name='employee_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='employee name'),
        ),
        migrations.AddField(
            model_name='contact',
            name='job_description',
            field=models.TextField(blank=True, verbose_name='job description'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('address', 'address'), ('social', 'social'), ('employee', 'employee')], max_length=16, verbose_name='type'),
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='image')),
                ('link_url', models.URLField(blank=True, verbose_name='link URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'banners',
                'ordering': ['sort_order', 'title'],
                'indexes': [models.Index(fields=['is_active'], name='banner_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='logo')),
                ('url', models.URLField(verbose_name='website URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'partner',
                'verbose_name_plural': 'partners',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['is_active'], name='partner_active_idx'), models.Index(fields=['sort_order'], name='partner_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='CompanyHistoryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('year', models.PositiveIntegerField(verbose_name='year')),
                ('description', models.TextField(verbose_name='description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_entries', to='common.companyinfo', verbose_name='company')),
            ],
            options={
                'verbose_name': 'company history entry',
                'verbose_name_plural': 'company history entries',
                'ordering': ['year'],
                'indexes': [models.Index(fields=['year'], name='company_history_year_idx')],
            },
        ),
    ]
