# Generated by Django 5.2.14 on 2026-09-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_seed_page_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='audio',
            field=models.FileField(blank=True, help_text='Локальный аудиофайл (например приветствие).', null=True, upload_to='company/audio/', verbose_name='company audio'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='certificate_image',
            field=models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='certificate image'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='video',
            field=models.FileField(blank=True, help_text='Локальный видеоролик о компании (mp4).', null=True, upload_to='company/videos/', verbose_name='company video'),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='video_url',
            field=models.URLField(blank=True, help_text='Не использовать для встраивания; предпочтителен FileField video.', verbose_name='video URL (устаревшее)'),
        ),
    ]
