# Generated by Django 5.2.14 on 2026-05-13 16:12

import apps.orders.models
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('reference_number', models.CharField(db_index=True, default=apps.orders.models._generate_order_reference, editable=False, max_length=64, unique=True, verbose_name='reference number')),
                ('status', models.CharField(choices=[('new', 'new'), ('paid', 'paid'), ('shipped', 'shipped'), ('completed', 'completed'), ('cancelled', 'cancelled')], default='new', max_length=16, verbose_name='status')),
                ('ordered_at', models.DateTimeField(auto_now_add=True, verbose_name='ordered at')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='total amount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to='users.employeeprofile', verbose_name='created by')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='users.customerprofile', verbose_name='customer')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='promotions.promocode', verbose_name='promo code')),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'indexes': [models.Index(fields=['status'], name='order_status_idx'), models.Index(fields=['customer'], name='order_customer_idx'), models.Index(fields=['ordered_at'], name='order_ordered_at_idx')],
            },
        ),
    ]
