# Generated by Django 5.2.14 on 2026-05-13 16:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0, verbose_name='quantity on hand')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'product stock',
                'verbose_name_plural': 'product stock',
                'indexes': [models.Index(fields=['quantity_on_hand'], name='stock_qty_idx')],
            },
        ),
    ]
