# Generated by Django 5.2.14 on 2026-05-13 17:03

import core.validators
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='company name')),
                ('legal_address', models.CharField(max_length=255, verbose_name='legal address')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('support_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='support email')),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_by_format_375_29], verbose_name='phone')),
                ('is_current', models.BooleanField(db_index=True, default=True, verbose_name='current record')),
            ],
            options={
                'verbose_name': 'company information',
                'verbose_name_plural': 'company information',
                'indexes': [models.Index(fields=['name'], name='companyinfo_name_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('is_current',), name='uniq_companyinfo_single_current')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('phone', 'phone'), ('email', 'email'), ('address', 'address'), ('social', 'social')], max_length=16, verbose_name='type')),
                ('value', models.CharField(max_length=255, verbose_name='value')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'indexes': [models.Index(fields=['type'], name='contact_type_idx'), models.Index(fields=['is_primary'], name='contact_primary_idx')],
                'constraints': [models.UniqueConstraint(fields=('type', 'value'), name='uniq_contact_type_value')],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.CharField(max_length=255, verbose_name='question')),
                ('answer', models.TextField(verbose_name='answer')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='sort order')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ entries',
                'ordering': ['sort_order', 'created_at'],
                'indexes': [models.Index(fields=['sort_order'], name='faq_sort_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'vacancy',
                'verbose_name_plural': 'vacancies',
                'indexes': [models.Index(fields=['is_active'], name='vacancy_active_idx'), models.Index(fields=['published_at'], name='vacancy_published_idx')],
            },
        ),
    ]
