# Generated by Django 5.2.14 on 2026-05-17 17:57

import core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_by_format_375_29], verbose_name='phone')),
                ('working_hours', models.CharField(blank=True, max_length=255, verbose_name='working hours')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'pickup point',
                'verbose_name_plural': 'pickup points',
                'indexes': [models.Index(fields=['is_active'], name='pickup_active_idx')],
            },
        ),
    ]
