# Generated by Django 5.2.14 on 2026-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_pickuppoint"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="staff_photos/%Y/%m/",
                verbose_name="employee photo",
            ),
        ),
    ]
