# Generated by Django 5.2.14 on 2026-09-07 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='summary',
            field=models.CharField(blank=True, help_text='Краткое содержание в одно предложение', max_length=500, verbose_name='summary'),
        ),
    ]
