# Generated by Django 5.2.14 on 2026-05-21 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="news/%Y/%m/",
                verbose_name="article image",
            ),
        ),
    ]
