# Generated by Django 5.2.14 on 2026-05-13 16:12

import core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('phone', models.CharField(max_length=20, validators=[core.validators.validate_phone_by_format_375_29], verbose_name='phone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='address')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'supplier',
                'verbose_name_plural': 'suppliers',
                'indexes': [models.Index(fields=['name'], name='supplier_name_idx'), models.Index(fields=['is_active'], name='supplier_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'phone'), name='uniq_supplier_name_phone')],
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('last_purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='last purchase price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_links', to='catalog.product', verbose_name='product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='suppliers.supplier', verbose_name='supplier')),
            ],
            options={
                'verbose_name': 'product supplier link',
                'verbose_name_plural': 'product supplier links',
                'indexes': [models.Index(fields=['product', 'supplier'], name='product_supplier_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'supplier'), name='uniq_product_supplier')],
            },
        ),
    ]
