# Generated by Django 5.2.14 on 2026-05-13 16:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='code')),
                ('discount_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='discount percent')),
                ('valid_from', models.DateField(verbose_name='valid from')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='max uses')),
                ('current_uses', models.PositiveIntegerField(default=0, verbose_name='current uses')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('customers', models.ManyToManyField(blank=True, related_name='promo_codes', to='users.customerprofile', verbose_name='eligible customers')),
            ],
            options={
                'verbose_name': 'promo code',
                'verbose_name_plural': 'promo codes',
                'indexes': [models.Index(fields=['code'], name='promocode_code_idx'), models.Index(fields=['is_active'], name='promocode_active_idx'), models.Index(fields=['valid_from', 'valid_until'], name='promocode_valid_idx')],
            },
        ),
    ]
